package com.example.booking.controller;
import com.example.booking.dto.*; import com.example.booking.entity.ReservationStatus; import com.example.booking.service.ReservationService; import jakarta.validation.Valid; import org.springframework.data.domain.*; import org.springframework.http.*; import org.springframework.security.core.Authentication; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import java.math.BigDecimal;
@RestController @RequestMapping("/api/reservations") public class ReservationController{
 private final ReservationService service;public ReservationController(ReservationService s){service=s;}
 @PostMapping public ResponseEntity<ReservationResponse>create(@Valid@RequestBody ReservationRequest r,Authentication a){return ResponseEntity.status(HttpStatus.CREATED).body(service.create(a.getName(),r));}
 @GetMapping("/mine")public Page<ReservationResponse>mine(@RequestParam(required=false)ReservationStatus status,@RequestParam(required=false)BigDecimal minPrice,@RequestParam(required=false)BigDecimal maxPrice,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="10")int size,@RequestParam(required=false)String sortBy,@RequestParam(defaultValue="asc")String direction,Authentication a){return service.userReservations(a.getName(),status,minPrice,maxPrice,pageable(page,size,sortBy,direction));}
 @GetMapping("/{id}")public ReservationResponse getMine(@PathVariable Long id,Authentication a){return service.getForUser(id,a.getName());}
 @PostMapping("/admin")@PreAuthorize("hasRole('ADMIN')")public ResponseEntity<ReservationResponse>adminCreate(@Valid@RequestBody AdminReservationRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(service.adminCreate(r));}
 @GetMapping("/admin")@PreAuthorize("hasRole('ADMIN')")public Page<ReservationResponse>all(@RequestParam(required=false)ReservationStatus status,@RequestParam(required=false)BigDecimal minPrice,@RequestParam(required=false)BigDecimal maxPrice,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="10")int size,@RequestParam(required=false)String sortBy,@RequestParam(defaultValue="asc")String direction){return service.adminReservations(status,minPrice,maxPrice,pageable(page,size,sortBy,direction));}
 @GetMapping("/admin/{id}")@PreAuthorize("hasRole('ADMIN')")public ReservationResponse adminGet(@PathVariable Long id){return service.adminGet(id);}
 @PutMapping("/admin/{id}")@PreAuthorize("hasRole('ADMIN')")public ReservationResponse update(@PathVariable Long id,@Valid@RequestBody AdminReservationRequest r){return service.adminUpdate(id,r);}
 @DeleteMapping("/admin/{id}")@PreAuthorize("hasRole('ADMIN')")public ResponseEntity<Void>delete(@PathVariable Long id){service.adminDelete(id);return ResponseEntity.noContent().build();}
 private Pageable pageable(int page,int size,String sortBy,String direction){if(page<0||size<1||size>100)throw new IllegalArgumentException("page must be >=0 and size must be 1..100");if(sortBy==null||sortBy.isBlank())return PageRequest.of(page,size);Sort s="desc".equalsIgnoreCase(direction)?Sort.by(sortBy).descending():Sort.by(sortBy).ascending();return PageRequest.of(page,size,s);}
}
